import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "sign_in": "Sign In",
          "sign_up": "Sign Up",
          "log_out": "Log Out",
          "email": "Email Address",
          "forget_password": "Forget Password ?",
          "reset_password": "Reset Your Password",
          "otp": "Enter your OTP",
          "otp_sent_text": "An OTP has been sent to your email, Please check your email.",
          "sent_request": "Sent Request",
          "remember_password": "Remember the password?",
          "verified_email_text": "Enter the email address associated with your account.",
          "name": "Name",
          "password": "Password",
          "confirm_password": "Confirm Password",
          "phone": "Phone",
          "Don't have an account? ": "Don't have an account",
          "Already have an account?  ": "Already have an account?  ",
          "phone_error": "Please Enter your Phone Number.",
          "password_error": "Please Enter Password.",
          "confirm_pass_error": "Please Enter Confirm Password",
          "otp_error": "Please Enter OTP",
          "email_error": "Please Enter Your Email",
          "wrong_email_error": "Sorry, you entered the wrong email",
          "pass_did_not_match_error": "Sorry, Password doesn't match",
          "wrong_data_insert_error": "Sorry, You entered wrong Information",
          "password_length_error": "Sorry,Password at lest 6 digit",
          "AppBar": "AppBar",
          "all_sales": "All Sales",
          "language_change": "Language Change",
          "theme_change": "Theme Change",
          "setting": "Settings",
          "user_info": "User Information",
          "search": "Search here",
          "category": "Category",
          "category_list": "Category",
          "trending": "Trending",
          "flash_sale": "Flash Sale",
          "just_for_you": "Just For You",
          "see_more": "See More",
          "shopping_cart": "Shopping Cart",
          "checkout": "Checkout",
          "shipping_info": "Shipping Information",
          "shipping_address": "Shipping Address",
          "personal_info": "Personal Information",
          "pricing_info": "Pricing Information",
          "house/road address": "House/Road Address",
          "post_code": "Postal code",
          "address": "Address",
          "city": "City",
          "district": "District",
          "division": "Division",
          "next": "Next",
          "summary": "Summary",
          "subtotal": "Subtotal ",
          "discount": "Discount",
          "shipping_charge": "Shipping Charge",
          "cash_on_delivery": "Cash On Delivery",
          "total_payable": "Payable Amount",
          "total_amount": "Total Amount",
          "continue": "Continue",
          "successful": "Successful",
          "thanks": "Thank You",
          "order_successful": "Order Successful",
          "my_fav_item_list": "My Favorite Products",
          "description": "Description",
          "related_product": "Related Products",
          "product_description": "Product Description",
          "product_specification": "Product Specification",
          "add_to_cart": "Add to Cart",
          "buy_now": "Buy Now",
          "Profile": "Profile",
          "Order": "Order",
          "Confirmed": "Confirmed",
          "Canceled": "Canceled",
          "Delivered": "Delivered",
          "Estimated Delivery": "Estimated Delivery on",
          "profile_edit": "Profile Edit",
          "edit": "Edit",
          "Let's get start..": " Let's get start",
          "Total Product": "Total Product",
          "welcome_heading": "Find your favorite products",
          "welcome_quotes": "“We see our customers as invited guests to a party, and we are the hosts. It’s our job every day to make every important aspect of the customer experience a little bit better.”",
          "welcome_quotes_writer": "- Jeff Bezos, Founder of Amazon",
          "welcome_button": "Login or Registration",
          "skip": "Skip",
          "payment_method" : "Payment Method",
          "payment_confirmation" : "Confirmation",
          "payment_confirmation_message" : "Do you want to submit an order for Cash on Delivery?",
          "cancel" : "Cancel",
          "confirm" : "Confirm",
          "continue_shopping" : "Continue Shopping",
          "email_or_phone" : "Email or Phone",
          "change_password" : "Change Password",
          "current_password" : "Current Password",
          "new_password" : "New Password",
          "my_orders" : "My Orders",
          "ongoing" : "OnGoing",
          "delivered" : "Delivered",
          "returned" : "Returned",
          "delete_account" : "Account Delete",
          "delete" : "Delete",

        },
        "bn_BD": {
          "sign_in": "সাইন ইন",
          "sign_up": "রেজিস্ট্রেশন ",
          "log_out": "লগ আউট",
          "forget_password": "পাসওয়ার্ড ভুলে গেছেন ?",
          "sent_request": "অনুরোধ পাঠান",
          "reset_password": "পাসওয়ার্ড রিসেট করুন",
          "otp": "আপনার OTP লিখুন",
          "remember_password": "পাসওয়ার্ড  মনে পড়ছে ?",
          "verified_email_text": "আপনার অ্যাকাউন্টের সাথে যুক্ত ইমেইল ঠিকানা লিখুন |",
          "otp_sent_text": "আপনার ইমেলে একটি OTP পাঠানো হয়েছে, অনুগ্রহ করে আপনার ইমেইল চেক করুন.",
          "phone_error": "দয়া করে আপনার ফোন নম্বর প্রবেশ করুন,",
          "password_error": "দয়া করে পাসওয়ার্ড  প্রবেশ করুন,",
          "confirm_pass_error": "দয়া করে আরেকবার পাসওয়ার্ড  প্রবেশ করুন,",
          "otp_error": "দয়া করে OTP প্রবেশ করুন,",
          "email_error": "দয়া করে  আপনার ইমেইল প্রবেশ করুন,",
          "wrong_email_error": "দুঃখিত ,আপনি ভুল ইমেইল প্রবেশ করেছেন,",
          "pass_did_not_match_error": "দুঃখিত,পাসওয়ার্ড মেলে না",
          "wrong_data_insert_error": "দুঃখিত, আপনি ভুল তথ্য প্রবেশ করেছেন। ",
          "password_length_error": "দুঃখিত, পাসওয়ার্ড কমপক্ষে 6 সংখ্যা,",
          "AppBar": "অ্যাপবার",
          "all_sales": "সমস্ত বিক্রয়",
          "language_change": "ভাষা পরিবর্তন",
          "theme_change": "থিম পরিবর্তন",
          "setting": "সেটিংস",
          "user_info": "ব্যবহারকারীর তথ্য",
          "email": "ইমেইল ঠিকানা",
          "address": "ঠিকানা",
          "name": "নাম",
          "password": "পাসওয়ার্ড",
          "confirm_password": "কন্ফার্ম পাসওয়ার্ড",
          "phone": "মোবাইল নাম্বার ",
          "Don't have an account? ": "কোনো অ্যাকাউন্ট নেই?",
          "Already have an account?  ": "ইতিমধ্যে একটা একাউন্ট আছে ?",
          "search": "এখানে খুঁজুন",
          "category": "ক্যাটাগরি",
          "category_list": "ক্যাটাগরি লিস্ট",
          "trending": "ট্রেন্ডিং প্রোডাক্ট",
          "flash_sale": "ফ্ল্যাশ সেল",
          "just_for_you": "শুধু আপনার জন্য",
          "see_more": "আরো দেখুন ",
          "shopping_cart": "শপিং কার্ট ",
          "checkout": "চেকআউট",
          "shipping_info": "শিপিং তথ্য",
          "shipping_address": "শিপিং ঠিকানা",
          "personal_info": "ব্যক্তিগত তথ্য",
          "pricing_info": "মূল্য তথ্য",
          "house/road address": "বাড়ি/রাস্তার ঠিকানা",
          "post_code": "পোস্ট কোড ",
          "city": "সিটি",
          "district": "জেলা",
          "division": "বিভাগ",
          "next": "পরবর্তী ",
          "summary": "সারসংক্ষেপ ",
          "subtotal": "সাবটোটাল ",
          "discount": "ডিসকাউন্ট",
          "shipping_charge": "শিপিং চার্জ ",
          "cash_on_delivery": "ক্যাশ অন ডেলিভারি",
          "total_payable": "মোট প্রদেয় পরিমাণ",
          "total_amount": "মোট মূল্য",
          "continue": "চালিয়ে যান",
          "successful": "সফল হয়েছে",
          "thanks": "ধন্যবাদ",
          "order_successful": "অর্ডার সফল ",
          "my_fav_item_list": "আমার পছন্দের পণ্যগুলি",
          "description": "পণ্যের বিবরণ",
          "related_product": "আরো দেখুন",
          "product_description": "পণ্যের বর্ণনা",
          "product_specification": "স্পেসিফিকেশন",
          "add_to_cart": "কার্টে যোগ করুন",
          "buy_now": "এখনই কিনুন",
          "Profile": "প্রোফাইল ",
          "Order": "অর্ডার  ",
          "Confirmed": "কনফার্ম ",
          "Canceled": "বাতিল ",
          "Delivered": "ডেলিভারি ",
          "Estimated Delivery": "আনুমানিক ডেলিভারি",
          "profile_edit": " প্রোফাইল এডিট",
          "edit": "এডিট করুন",
          "Let's get start..": "চলুন শুরু করা যাক ",
          "Total Product": "মোট  পণ্য  সংখ্যা ",
          "welcome_heading": "আপনার প্রিয় পণ্য খুঁজুন",
          "welcome_quotes": "“আমরা আমাদের গ্রাহকদের একটি পার্টিতে আমন্ত্রিত অতিথি হিসাবে দেখি এবং আমরাই হোস্ট। গ্রাহকদের অভিজ্ঞতার প্রতিটি গুরুত্বপূর্ণ দিককে একটু ভালো করে তোলাই প্রতিদিন আমাদের কাজ।”",
          "welcome_quotes_writer": "- জেফ বেজোস, অ্যামাজনের প্রতিষ্ঠাতা",
          "welcome_button": "লগইন বা নিবন্ধন করুন",
          "skip": "এড়িয়ে যান",
          "payment_method" : "মূল্যপরিশোধ পদ্ধতি",
          "payment_confirmation" : "নিশ্চিতকরণ",
          "payment_confirmation_message" : "আপনি কি ক্যাশ অন ডেলিভারিতে অর্ডার সাবমিট করতে চান?",
          "cancel" : "বাতিল করুন",
          "confirm" : "নিশ্চিত করুন",
          "continue_shopping" : "কেনাকাটা চালিয়ে যান",
          "email_or_phone" : "ইমেইল / মোবাইল নাম্বার",
          "change_password" : "পাসওয়ার্ড পরিবর্তন",
          "current_password" : "বর্তমান পাসওয়ার্ড",
          "new_password" : "নতুন পাসওয়ার্ড",
          "my_orders" : "আমার অর্ডার",
          "delivered" : "ডেলিভারি",
          "ongoing" : "চলমান",
          "returned" : "ফেরত ",
          "delete_account" : "একাউন্ট ডিলিট",
          "delete" : "ডিলিট",

        },
      };
}
